version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: albaring-mysql-test
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: test!32
      TZ: Asia/Seoul
      MYSQL_DATABASE: albaring_test
      MYSQL_USER: albaring_test
      MYSQL_PASSWORD: test!32
    command:
      - --character-set-server=UTF8MB4
      - --collation-server=UTF8MB4_UNICODE_CI
      - --lower_case_table_names=1

  redis:
    image: redis:6.2
    container_name: albaring-redis-test
    ports:
      - 6380:6379
    command: redis-server --appendonly yes
