server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - "health"
          - "info"
          - "prometheus"
  endpoint:
    prometheus:
      enabled: true