server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        jdbc:
          batch_size: 100
    database-platform: org.hibernate.dialect.MySQL57Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/albaring_local?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: albaring_local
    password: local!32
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

security:
  jwt:
    token:
      secret-key: albaring-local-secret-key
      access-token-expire-length: 3600000 # 1 hour for access token
      refresh-token-expire-length: 1209600000 # 2 weeks for refresh token

kakao:
  auth:
    token-uri: https://kauth.kakao.com/oauth/token
    client-id: 07312ebdd7584a1895d57673e65fc17c
    client-secret: u4F1QXxD0hqZeuNasn87k7X2NJdBOQBc
    redirect-uri: http://localhost:8080/api/auth/kakao/callback

  user:
    profile-uri: https://kapi.kakao.com/v2/user/me

naver:
  auth:
    token-uri: https://nid.naver.com/oauth2.0/token
    client-id: yGXd9qASyW8v2W65giHQ
    client-secret: ZalbTzUkWr
    redirect-uri: http://localhost:8080/api/auth/naver/callback

  user:
    profile-uri: https://openapi.naver.com/v1/nid/me

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.type.descriptor.sql: trace

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /api/**